name: Build APK

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup JDK
                uses: actions/setup-java@v4
                with:
                    java-version: '18'
                    distribution: 'corretto'
                    cache: gradle

            -   name: Set version
                run: echo -e "\nVN=${{ github.event.release.tag_name }}" >> keystore.properties && cat keystore.properties

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Build APK
                run: ./gradlew app:aR

            -   name: Rename APK
                run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/peanut-pass-${{ github.event.release.tag_name }}.apk

            -   name: Upload Release Asset
                uses: softprops/action-gh-release@v2
                with:
                    files: |
                        app/build/outputs/apk/release/peanut-pass-${{ github.event.release.tag_name }}.apk
                        app/build/outputs/mapping/release/mapping.txt