name: Build APK

on:
    workflow_dispatch:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                    submodules: 'true'

            -   name: set up JDK
                uses: actions/setup-java@v4
                with:
                    java-version: '18'
                    distribution: 'corretto'
                    cache: gradle

            -   name: Get version
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

            -   name: Set version
                run: echo -e "\nVN=${{ steps.get_version.outputs.VERSION }}" >> keystore.properties && cat keystore.properties

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Build APK
                run: ./gradlew app:aR

            - name: Rename APK
              run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/peanut-pass-${{ steps.get_version.outputs.VERSION }}.apk

            -   name: Upload APK
                uses: softprops/action-gh-release@v2
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    files: |
                        app/build/outputs/apk/release/peanut-pass-${{ steps.get_version.outputs.VERSION }}.apk
                        app/build/outputs/mapping/release/mapping.txt